// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInventoryHisab.DAL;

#nullable disable

namespace SmartInventoryHisab.DAL.Migrations
{
    [DbContext(typeof(SmartInventoryDbContext))]
    partial class SmartInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6139),
                            CurrentStock = 6,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 1",
                            Price = 80.4536491867405m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6158),
                            CurrentStock = 25,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 2",
                            Price = 372.20418236321m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 21, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6164),
                            CurrentStock = 25,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 3",
                            Price = 138.660698946873m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 14, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6168),
                            CurrentStock = 1,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 4",
                            Price = 268.725549913349m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 8, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6172),
                            CurrentStock = 4,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 5",
                            Price = 86.0965401195439m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 2, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6177),
                            CurrentStock = 35,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 6",
                            Price = 32.0735690193593m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 23, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6220),
                            CurrentStock = 9,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 7",
                            Price = 268.206857022926m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 7, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6224),
                            CurrentStock = 0,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 8",
                            Price = 420.532575990321m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 31, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6227),
                            CurrentStock = 7,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 9",
                            Price = 202.286845851823m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 9, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6234),
                            CurrentStock = 5,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 10",
                            Price = 323.228192186555m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 14, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6237),
                            CurrentStock = 7,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 11",
                            Price = 334.072953697328m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 14, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6241),
                            CurrentStock = 21,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 12",
                            Price = 35.3973440385411m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 30, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6244),
                            CurrentStock = 18,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 13",
                            Price = 16.6268874828829m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 3, 9, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6247),
                            CurrentStock = 23,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 14",
                            Price = 45.4714708102268m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 3, 8, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6250),
                            CurrentStock = 24,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 15",
                            Price = 266.748119488707m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 31, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6254),
                            CurrentStock = 3,
                            Description = "High quality electronics product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Electronics Item 16",
                            Price = 11.5370042536114m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 11, 13, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6257),
                            CurrentStock = 23,
                            Description = "High quality stationery product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Stationery Item 17",
                            Price = 474.485383343178m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 9, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6261),
                            CurrentStock = 7,
                            Description = "High quality electronics product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Electronics Item 18",
                            Price = 196.383614636205m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 5, 15, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6265),
                            CurrentStock = 14,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 19",
                            Price = 210.349496305152m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 4, 22, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6269),
                            CurrentStock = 44,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 20",
                            Price = 19.7060832240181m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 10, 23, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6272),
                            CurrentStock = 5,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 21",
                            Price = 91.1814030544746m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 15, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6277),
                            CurrentStock = 6,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 22",
                            Price = 84.274555348919m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 7, 11, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6280),
                            CurrentStock = 38,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 23",
                            Price = 503.510795986983m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 9, 1, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6283),
                            CurrentStock = 49,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 24",
                            Price = 286.030006714179m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 25, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6286),
                            CurrentStock = 1,
                            Description = "High quality furniture product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Furniture Item 25",
                            Price = 474.531421179199m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 10, 30, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6290),
                            CurrentStock = 29,
                            Description = "High quality electronics product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Electronics Item 26",
                            Price = 118.061852216749m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 12, 23, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6293),
                            CurrentStock = 5,
                            Description = "High quality stationery product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Stationery Item 27",
                            Price = 70.6966738406088m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 3, 7, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6296),
                            CurrentStock = 0,
                            Description = "High quality kitchen product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Kitchen Item 28",
                            Price = 422.91395989848m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 5, 24, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6300),
                            CurrentStock = 46,
                            Description = "High quality stationery product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Stationery Item 29",
                            Price = 129.036826826184m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 0, 59, 478, DateTimeKind.Utc).AddTicks(6303),
                            CurrentStock = 31,
                            Description = "High quality appliance product for daily use.",
                            ImageUrl = "/images/products/placeholder.png",
                            Name = "Appliance Item 30",
                            Price = 327.237977086212m
                        });
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInventoryHisab.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.Purchase", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.Sale", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartInventoryHisab.Model.StockTransaction", b =>
                {
                    b.HasOne("SmartInventoryHisab.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
